"""Browser session — a real logged-in Chrome, driven by Playwright.

Key constraints, verified 2026-07-13:

* Chrome 136+ refuses CDP automation against the OS-default profile, and the
  live profile dir is locked while Chrome runs. So we NEVER touch
  ``~/Library/.../Chrome/Default``; we use a dedicated, tool-owned profile dir
  under ``~/.tiktok-saver/profile`` that the user logs into once.
* ``channel="chrome"`` uses the real installed Chrome, not bundled Chromium —
  a materially weaker anti-bot fingerprint than Chromium, and the single
  biggest lever we have short of a full stealth patch.
* ``headless=False`` — TikTok's anti-bot challenges headless hard; a low-volume
  first-party run has no reason to hide.

The tool owns the profile, so cookies persist between ``login``, ``enumerate``
and ``download`` with no system-Chrome coupling.
"""
from __future__ import annotations

import contextlib
from pathlib import Path
from typing import Iterator

DEFAULT_PROFILE_DIR = Path.home() / ".tiktok-saver" / "profile"
TIKTOK_HOME = "https://www.tiktok.com/"

# A current desktop Chrome UA. channel="chrome" already supplies a real UA;
# this is only a fallback if a caller forces Chromium.
_UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36"
)


@contextlib.contextmanager
def browser_context(
    profile_dir: str | Path = DEFAULT_PROFILE_DIR,
    headless: bool = False,
    channel: str = "chrome",
) -> Iterator["BrowserContext"]:  # noqa: F821 (Playwright type, imported lazily)
    """Yield a persistent Playwright context bound to the tool's profile.

    Imported lazily so ``--help`` and the pure-logic modules don't require
    Playwright to be installed.
    """
    from playwright.sync_api import sync_playwright

    profile_dir = Path(profile_dir)
    profile_dir.mkdir(parents=True, exist_ok=True)

    with sync_playwright() as p:
        launch_kwargs = dict(
            user_data_dir=str(profile_dir),
            headless=headless,
            args=["--disable-blink-features=AutomationControlled"],
            viewport={"width": 1280, "height": 900},
        )
        # channel="chrome" fails if Chrome isn't installed; fall back to bundled
        # Chromium with a spoofed UA so the tool still runs on a bare box.
        try:
            ctx = p.chromium.launch_persistent_context(channel=channel, **launch_kwargs)
        except Exception:
            ctx = p.chromium.launch_persistent_context(
                user_agent=_UA, **launch_kwargs
            )
        try:
            yield ctx
        finally:
            with contextlib.suppress(Exception):
                ctx.close()


def is_logged_in(context) -> bool:
    """Heuristic: TikTok sets a ``sessionid`` cookie only for a logged-in user."""
    for c in context.cookies():
        if c.get("name") == "sessionid" and c.get("value"):
            return True
    return False


def export_cookies_txt(context, out_path: str | Path) -> Path:
    """Write the context's tiktok.com cookies as a Netscape cookies.txt.

    Fed to yt-dlp / gallery-dl via ``--cookies`` so the download step needs no
    live browser and no fragile ``--cookies-from-browser`` profile parsing.
    """
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Netscape HTTP Cookie File", "# generated by tiktok-saver", ""]
    for c in context.cookies():
        domain = c.get("domain", "")
        if "tiktok" not in domain:
            continue
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        expires = int(c.get("expires") or 0)
        if expires <= 0:
            expires = 0
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(
            "\t".join([domain, include_sub, path, secure, str(expires), name, value])
        )
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out_path
